In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model

In [34]:
for col, values in convert_dict.items():
    df[col] = df[col].map({value: i for i, value in enumerate(values)})

In [80]:
# show the columns that have large std
df = pd.read_csv('data.csv')
# Age
# MonthlyIncome
# DailyRate
# EmployeeNumber
# MonthlyRate
# HourlyRate
df = df[['Age', 'MonthlyIncome', 'DailyRate', 'MonthlyRate', 'HourlyRate', 'Education']]
df

Age  MonthlyIncome  DailyRate  MonthlyRate  HourlyRate  Education
0      41           5993       1102        19479          94          2
1      49           5130        279        24907          61          1
2      37           2090       1373         2396          92          2
3      33           2909       1392        23159          56          4
4      27           3468        591        16632          40          1
...   ...            ...        ...          ...         ...        ...
1465   36           2571        884        12290          41          2
1466   39           9991        613        21457          42          1
1467   27           6142        155         5174          87          3
1468   49           5390       1023        13243          63          3
1469   34           4404        628        10228          82          3

[1470 rows x 6 columns]

In [81]:
Y = df['Education']
X = df.drop(['Education'], axis=1)

In [82]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Random Forest model
rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train_scaled, Y_train)

# Make predictions on the test set
Y_pred_rf = rf_classifier.predict(X_test_scaled)

In [83]:
imp = np.array(rf_classifier.feature_importances_)
print(imp)

[0.17589393 0.22002293 0.2082885  0.20780742 0.18798722]


In [84]:
# Evaluate the Random Forest model
accuracy_rf = accuracy_score(Y_test, Y_pred_rf)
conf_matrix_rf = confusion_matrix(Y_test, Y_pred_rf)
classification_rep = classification_report(Y_test, Y_pred_rf, zero_division=1)

print(f"Random Forest Model Accuracy: {accuracy_rf}")
print("Random Forest Confusion Matrix:")
print(conf_matrix_rf)
print("Random Forest Classification Report:")
print(classification_rep)

Random Forest Model Accuracy: 0.36054421768707484
Random Forest Confusion Matrix:
[[ 5  3 11  3  0]
 [ 1  8 29 25  0]
 [ 6  5 66 41  0]
 [ 2 10 42 27  0]
 [ 0  1  4  5  0]]
Random Forest Classification Report:
              precision    recall  f1-score   support

           1       0.36      0.23      0.28        22
           2       0.30      0.13      0.18        63
           3       0.43      0.56      0.49       118
           4       0.27      0.33      0.30        81
           5       1.00      0.00      0.00        10

    accuracy                           0.36       294
   macro avg       0.47      0.25      0.25       294
weighted avg       0.37      0.36      0.34       294



In [101]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_fscore_support
from sklearn.inspection import permutation_importance
from sklearn.decomposition import PCA

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# use PCA to reduce the dimensionality of the data
# pca = PCA(n_components=2)
# X_train_scaled = pca.fit_transform(X_train_scaled)
# X_test_scaled = pca.transform(X_test_scaled)

svm_classifier = SVC(kernel='linear', random_state=42)
svm_classifier.fit(X_train_scaled, Y_train)
# Make predictions on the test set
Y_pred_svm = svm_classifier.predict(X_test_scaled)

# Evaluate the SVM model
accuracy_svm = accuracy_score(Y_test, Y_pred_svm)
conf_matrix_svm = confusion_matrix(Y_test, Y_pred_svm)
precision, recall, fscore, _ = precision_recall_fscore_support(Y_test, Y_pred_svm, average='weighted', zero_division=1)
                    # weights = pd.concat(weights, pd.DataFrame([i, j, k, l, m, accuracy_svm, precision, recall, fscore], columns=['Age', 'MonthlyIncome', 'DailyRate', 'MonthlyRate', 'HourlyRate', 'Accuracy', 'Precision', 'Recall', 'F-score']))
                    # weights.loc[len(weights.index)] = [i, j, k, l, m, accuracy_svm, precision, recall, fscore] 
print(f"SVM Model Accuracy: {accuracy_svm}")
# print(svm_classifier.coef_)
print("SVM Confusion Matrix:")
print(conf_matrix_svm)
print(f"SVM Precision: {precision:.4f}")
print(f"SVM Recall: {recall:.4f}")
print(f"SVM F-score: {fscore:.4f}")
print("SVM Classification Report:")
print(classification_report(Y_test, Y_pred_svm, zero_division=1))

SVM Model Accuracy: 0.4013605442176871
SVM Confusion Matrix:
[[  0   0  22   0   0]
 [  0   0  63   0   0]
 [  0   0 118   0   0]
 [  0   0  81   0   0]
 [  0   0  10   0   0]]
SVM Precision: 0.7597
SVM Recall: 0.4014
SVM F-score: 0.2299
SVM Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.00      0.00        22
           2       1.00      0.00      0.00        63
           3       0.40      1.00      0.57       118
           4       1.00      0.00      0.00        81
           5       1.00      0.00      0.00        10

    accuracy                           0.40       294
   macro avg       0.88      0.20      0.11       294
weighted avg       0.76      0.40      0.23       294



In [53]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train SVM with RBF kernel model
svm_rbf_classifier = SVC(kernel='rbf', random_state=42)
svm_rbf_classifier.fit(X_train_scaled, Y_train)

# Make predictions on the test set
Y_pred_svm_rbf = svm_rbf_classifier.predict(X_test_scaled)

# Evaluate the SVM with RBF kernel model
accuracy_svm_rbf = accuracy_score(Y_test, Y_pred_svm_rbf)
conf_matrix_svm_rbf = confusion_matrix(Y_test, Y_pred_svm_rbf)
classification_rep_svm_rbf = classification_report(Y_test, Y_pred_svm_rbf, zero_division=1)  # Adding zero_division parameter

print(f"SVM with RBF Kernel Model Accuracy: {accuracy_svm_rbf}")
print("SVM with RBF Kernel Confusion Matrix:")
print(conf_matrix_svm_rbf)
print("SVM with RBF Kernel Classification Report:")
print(classification_rep_svm_rbf)

SVM with RBF Kernel Model Accuracy: 0.3707482993197279
SVM with RBF Kernel Confusion Matrix:
[[  0   0  22   0   0]
 [  0   0  57   6   0]
 [  0   0 102  16   0]
 [  0   0  74   7   0]
 [  0   0  10   0   0]]
SVM with RBF Kernel Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.00      0.00        22
           2       1.00      0.00      0.00        63
           3       0.38      0.86      0.53       118
           4       0.24      0.09      0.13        81
           5       1.00      0.00      0.00        10

    accuracy                           0.37       294
   macro avg       0.73      0.19      0.13       294
weighted avg       0.54      0.37      0.25       294



In [54]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Decision Tree model
tree_classifier = DecisionTreeClassifier(random_state=42)
tree_classifier.fit(X_train_scaled, Y_train)

# Make predictions on the test set
Y_pred_tree = tree_classifier.predict(X_test_scaled)

# Evaluate the Decision Tree model
accuracy_tree = accuracy_score(Y_test, Y_pred_tree)
conf_matrix_tree = confusion_matrix(Y_test, Y_pred_tree)
classification_rep_tree = classification_report(Y_test, Y_pred_tree, zero_division=1)  # Adding zero_division parameter

print(f"Decision Tree Model Accuracy: {accuracy_tree}")
print("Decision Tree Confusion Matrix:")
print(conf_matrix_tree)
print("Decision Tree Classification Report:")
print(classification_rep_tree)


Decision Tree Model Accuracy: 0.3197278911564626
Decision Tree Confusion Matrix:
[[ 8  5  7  0  2]
 [ 4 13 22 20  4]
 [11 14 49 42  2]
 [ 9 13 31 24  4]
 [ 1  4  2  3  0]]
Decision Tree Classification Report:
              precision    recall  f1-score   support

           1       0.24      0.36      0.29        22
           2       0.27      0.21      0.23        63
           3       0.44      0.42      0.43       118
           4       0.27      0.30      0.28        81
           5       0.00      0.00      1.00        10

    accuracy                           0.32       294
   macro avg       0.24      0.26      0.45       294
weighted avg       0.33      0.32      0.36       294



In [55]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Gradient Boosting model
gb_classifier = GradientBoostingClassifier(random_state=42)
gb_classifier.fit(X_train_scaled, Y_train)

# Make predictions on the test set
Y_pred_gb = gb_classifier.predict(X_test_scaled)

# Evaluate the Gradient Boosting model
accuracy_gb = accuracy_score(Y_test, Y_pred_gb)
conf_matrix_gb = confusion_matrix(Y_test, Y_pred_gb)
classification_rep_gb = classification_report(Y_test, Y_pred_gb, zero_division=1)  # Adding zero_division parameter

print(f"Gradient Boosting Model Accuracy: {accuracy_gb}")
print("Gradient Boosting Confusion Matrix:")
print(conf_matrix_gb)
print("Gradient Boosting Classification Report:")
print(classification_rep_gb)

Gradient Boosting Model Accuracy: 0.35034013605442177
Gradient Boosting Confusion Matrix:
[[ 4  0 14  4  0]
 [ 2  4 32 25  0]
 [ 4  6 75 32  1]
 [ 2 10 49 20  0]
 [ 0  0  8  2  0]]
Gradient Boosting Classification Report:
              precision    recall  f1-score   support

           1       0.33      0.18      0.24        22
           2       0.20      0.06      0.10        63
           3       0.42      0.64      0.51       118
           4       0.24      0.25      0.24        81
           5       0.00      0.00      1.00        10

    accuracy                           0.35       294
   macro avg       0.24      0.23      0.42       294
weighted avg       0.30      0.35      0.34       294



In [56]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train k-Nearest Neighbors model
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train_scaled, Y_train)

# Make predictions on the test set
Y_pred_knn = knn_classifier.predict(X_test_scaled)

# Evaluate the k-Nearest Neighbors model
accuracy_knn = accuracy_score(Y_test, Y_pred_knn)
conf_matrix_knn = confusion_matrix(Y_test, Y_pred_knn)
classification_rep_knn = classification_report(Y_test, Y_pred_knn, zero_division=1)  # Adding zero_division parameter

print(f"k-Nearest Neighbors Model Accuracy: {accuracy_knn}")
print("k-Nearest Neighbors Confusion Matrix:")
print(conf_matrix_knn)
print("k-Nearest Neighbors Classification Report:")
print(classification_rep_knn)


k-Nearest Neighbors Model Accuracy: 0.2891156462585034
k-Nearest Neighbors Confusion Matrix:
[[ 0  7 11  4  0]
 [11 13 23 16  0]
 [12 21 59 26  0]
 [ 7 23 38 13  0]
 [ 2  2  3  3  0]]
k-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      1.00        22
           2       0.20      0.21      0.20        63
           3       0.44      0.50      0.47       118
           4       0.21      0.16      0.18        81
           5       1.00      0.00      0.00        10

    accuracy                           0.29       294
   macro avg       0.37      0.17      0.37       294
weighted avg       0.31      0.29      0.36       294



In [57]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train logistic regression model
logreg = LogisticRegression()
logreg.fit(X_train_scaled, Y_train)

# Make predictions on the test set
Y_pred = logreg.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
conf_matrix = confusion_matrix(Y_test, Y_pred)

print(f"Model Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)

Model Accuracy: 0.3401360544217687
Confusion Matrix:
[[ 0  0 20  2  0]
 [ 0  0 52 11  0]
 [ 0  0 90 28  0]
 [ 0  0 71 10  0]
 [ 0  0  9  1  0]]


In [58]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Naive Bayes model
nb_classifier = GaussianNB()
nb_classifier.fit(X_train_scaled, Y_train)

# Make predictions on the test set
Y_pred_nb = nb_classifier.predict(X_test_scaled)

# Evaluate the Naive Bayes model
accuracy_nb = accuracy_score(Y_test, Y_pred_nb)
conf_matrix_nb = confusion_matrix(Y_test, Y_pred_nb)
classification_rep_nb = classification_report(Y_test, Y_pred_nb, zero_division=1)  # Adding zero_division parameter

print(f"Naive Bayes Model Accuracy: {accuracy_nb}")
print("Naive Bayes Confusion Matrix:")
print(conf_matrix_nb)
print("Naive Bayes Classification Report:")
print(classification_rep_nb)

Naive Bayes Model Accuracy: 0.3469387755102041
Naive Bayes Confusion Matrix:
[[ 0  0 19  3  0]
 [ 0  0 50 13  0]
 [ 0  0 90 28  0]
 [ 0  0 69 12  0]
 [ 0  0  9  1  0]]
Naive Bayes Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.00      0.00        22
           2       1.00      0.00      0.00        63
           3       0.38      0.76      0.51       118
           4       0.21      0.15      0.17        81
           5       1.00      0.00      0.00        10

    accuracy                           0.35       294
   macro avg       0.72      0.18      0.14       294
weighted avg       0.53      0.35      0.25       294

